#!/bin/bash
# lowfi cicd post-commit hook script

# Function to initialize the project
initialize_project() {
    echo "Initializing lowfi CI/CD post-commit hook..."

    # Create logs directory if it doesn't exist
    if [ ! -d "logs" ]; then
        mkdir logs
        echo "Created logs directory."
    else
        echo "Logs directory already exists."
    fi

    # Create symlink for the post-commit hook
    if [ -f ".git/hooks/post-commit" ]; then
        echo "Post-commit hook already exists. Exiting initialization."
        exit 1
    fi

    ln "$(pwd)/$0" .git/hooks/post-commit
    chmod u+x .git/hooks/post-commit
    echo "Linked and set executable for post-commit hook."

    echo "Initialization complete."
}

# Check if the --init argument is provided
if [ "$1" == "--init" ]; then
    initialize_project
    exit 0
fi

# Main script functionality
TIMESTAMP=$(date +%d-%m-%y-%H-%M-%S)
log_path="./logs"
msg="$TIMESTAMP : lowfi automation complete."

# Ensure the logs directory exists
if [ ! -d "$log_path" ]; then
    mkdir -p "$log_path"
fi

# Log the message to both timestamped and latest log files
echo $msg >> "$log_path/lowfi-$TIMESTAMP.log"
echo $msg >> "$log_path/lowfi-latest.log"

echo "Log entry added: $msg"